version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./library_front
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: ./library_back
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=library_db
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
